priorityClassName: platform-cluster-critical
csi:
  cephFSKernelMountOptions: ms_mode=prefer-crc
  enableLiveness: true
  provisionerPriorityClassName: platform-cluster-critical
  pluginPriorityClassName: platform-node-critical
  serviceMonitor:
    enabled: true
image:
  repository: ghcr.io/rook/ceph
monitoring:
  enabled: true
resources:
  requests:
    memory: 128Mi # unchangable
    cpu: 100m # unchangable
  limits: {}
