---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minecraft-bedrock
spec:
  sourcePVC: minecraft-bedrock-ceph
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-block
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    parallelism: 2
    repository: minecraft-bedrock-volsync-secret
    retain:
      daily: 3
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
