---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  path: "./apps/base/rook-ceph/rook-ceph/app"
  wait: true
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  targetNamespace: rook-ceph
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  path: "./apps/base/rook-ceph/rook-ceph/cluster"
  wait: true
  targetNamespace: rook-ceph
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  # - name: volsync
  #   namespace: volsync-system
