---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent
  namespace: ai-system
spec:
  path: "./apps/base/ai-system/kagent/app"
  wait: false
  dependsOn:
    - name: kagent-crds
      namespace: ai-system
  targetNamespace: ai-system
  sourceRef:
    kind: ExternalArtifact
    name: kagent
    namespace: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent-crds
  namespace: ai-system
spec:
  path: "./apps/base/ai-system/kagent/crds"
  wait: false
  targetNamespace: ai-system
  sourceRef:
    kind: ExternalArtifact
    name: kagent-crds
    namespace: flux-system
