---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  decryption:
    provider: sops
  deletionPolicy: WaitForTermination
  interval: 30m
  timeout: 30m
  path: ./apps/overlays/cluster-00
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  patches:
    - # Set Kustomization defaults and HelmRelease defaults for all child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          decryption:
            provider: sops
          deletionPolicy: WaitForTermination
          interval: 30m
          retryInterval: 1m
          timeout: 3m
          prune: true
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: _
                spec:
                  install:
                    timeout: 10m
                    replace: true
                    crds: CreateReplace
                    createNamespace: true
                  upgrade:
                    remediation:
                      remediateLastFailure: true
                      retries: 3
                      strategy: rollback
                    cleanupOnFail: true
                    crds: CreateReplace
                  test:
                    enable: true
                  rollback:
                    recreate: true
                    force: true
                    cleanupOnFail: true
                  uninstall:
                    keepHistory: false
                  driftDetection:
                    mode: enabled
                  maxHistory: 3
              target:
                group: helm.toolkit.fluxcd.io
                kind: HelmRelease
                labelSelector: gitops.owncloud.ai/defaults!=disabled
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: gitops.owncloud.ai/defaults!=disabled
