---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kick-vision-hub
  namespace: game-servers
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: "./apps/base/game-servers/kick-vision-hub/app"
  prune: true
  wait: true
  sourceRef:
    kind: ExternalArtifact
    name: kick-vision-hub
    namespace: flux-system
  targetNamespace: game-servers
