---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt
spec:
  sourcePVC: zigbee2mqtt-cache-ceph
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-block
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    parallelism: 2
    repository: zigbee2mqtt-volsync-secret
    retain:
      daily: 3
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
