---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
stringData:
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ${MQTT_USER_USERNAME}
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ${MQTT_USER_PASSWORD}
