---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-bedrock-broadcaster
  namespace: game-servers
spec:
  dependsOn:
    - name: democratic-csi
      namespace: democratic-csi
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  path: "./apps/base/game-servers/minecraft-bedrock-broadcaster/app"
  wait: true
  targetNamespace: game-servers
  sourceRef:
    kind: ExternalArtifact
    name: minecraft-bedrock-broadcaster
    namespace: flux-system
