apiVersion: v1
kind: Secret
metadata:
  name: kguardian-openrouter
  namespace: kguardian
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:VfPIhu9/S1IUWj6b6SbuUQNAd9cRrfIZMFxZPexrBIH8UFhBRXhgqkTV/3U0orTPzvxgsTjWHjOWGMi6goxF5Z3PBRiTy3EjnA==,iv:cCLdf0eMXtCXn45fb2boGYHv2vPIL2H1t4Tdsh71Zco=,tag:TpFaaaceMDLJZXSUTzVyYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOG9wKzZSWEtKd0JkODFv
        M1JUeGJVZDZJV1RyWTVQWnpORExFVlM0WXhFCi91RjdPQXZBY3lqRXRFYzFremZp
        NEU0bFdJTWw3c0dDSnFMODRFVUptRUUKLS0tIG1QcTF6cE9qZHZUYTBqRzBYZkFD
        cXRCRVRTRnoyZGc3T3BqdGlMdDRJeEUKRbNbnVgLnXyN9Zd6rxyLiSO40nIJHnhR
        FiKL3SRjjfwLKhCNKdLxmX3wEVESTfqQ5OKGtCNxoh+gil+KxMoUqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19gj66fq5v2veu940ftyj4pkw0w5tgxgddlyqnd00pnjzyndevurqx70g4t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-04T03:59:54Z"
  mac: ENC[AES256_GCM,data:6uNbuQwQsgbvadoHrtYjazz4puDiuu4ecNA+WoMr6o7PlDrS2l8j1xTvzeJd5UsRlwpB1IzRtHCkqI040JLpRn+YBwoHWpE92GDE0udkpQHZYEnQp2sg+fGU7I/P2C2GsRkxdpaQNWGNa3qJIXN2Ploai0AF+Q7NGdGl0xhtWK8=,iv:CRL1ufZ1nLxzs074vqTESG9RGu02RLsESQkXhJywTxE=,tag:DZyvx2jIvWyJCSrJ02JUig==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
