---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-rcon-web
  namespace: game-servers
spec:
  dependsOn:
    - name: minecraft
      namespace: game-servers
  path: "./apps/base/game-servers/minecraft-rcon-web/app"
  wait: true
  targetNamespace: game-servers
  sourceRef:
    kind: ExternalArtifact
    name: minecraft-rcon-web
    namespace: flux-system
