---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emberstone-portal-captcha
  namespace: game-servers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: emberstone-portal-captcha
    template:
      data:
        CAPTCHA_KEY: "{{ .SITE_KEY }}"
        CAPTCHA_SECRET: "{{ .SECRET_KEY }}"
  dataFrom:
    - extract:
        key: emberstone
