---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cmangos-soap-creds
  namespace: game-servers
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cmangos-soap-creds
    template:
      data:
        SOAP_USER: "{{ .SOAP_USER }}"
        SOAP_PASSWORD: "{{ .SOAP_PASSWORD }}"
  dataFrom:
    - extract:
        key: cmangos
