---
image:
  repository: ghcr.io/xunholy/kustomize-mutating-webhook
replicas: 1
certManager:
  enabled: true
configMaps:
  - create: false
    name: cluster-config
secrets:
  - create: false
    name: cluster-secrets
env:
  LOG_LEVEL: debug
  AUTO_UPDATE_KUSTOMIZATIONS: "true"
  AUTO_UPDATE_EXCLUDE_NAMESPACES: "flux-system"
podDisruptionBudget:
  enabled: false
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
service:
  headless: false
