---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gha-runner-scale-set-controller
  labels:
    flux-defaults: "true"
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
  values:
    fullnameOverride: gha-runner-scale-set-controller
    replicaCount: 1
    priorityClassName: platform-cluster-critical
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"
    flags:
      logLevel: "debug"
      logFormat: "json"
