---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app crossplane
  namespace: crossplane-system
  labels:
    flux-defaults: "true"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: crossplane
  values:
    metrics:
      enabled: true
