---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: email
    groupBy:
      - namespace
      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "=~"
            value: "InfoInhibitor|Watchdog"
        continue: false
      - receiver: email
        matchers:
          - name: severity
            matchType: "=~"
            value: "critical|warning"
        continue: false
  receivers:
    - name: "null"
    - name: email
      emailConfigs:
        - to: "${PRIVATE_EMAIL}"
          from: "alertmanager@${CLUSTER_DOMAIN}"
          smarthost: "smtp-relay.home-system.svc.cluster.local:25"
          requireTLS: false
          sendResolved: true
          headers:
            - key: Subject
              value: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}'
  inhibitRules:
    - sourceMatch:
        - name: severity
          matchType: "="
          value: critical
      targetMatch:
        - name: severity
          matchType: "=~"
          value: warning|info
      equal:
        - namespace
        - alertname
    - sourceMatch:
        - name: alertname
          matchType: "="
          value: InfoInhibitor
      targetMatch:
        - name: severity
          matchType: "="
          value: info
      equal:
        - namespace
