---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-witherstorm-ceph
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
