image:
  repository: itzg/minecraft-bedrock-server
  tag: latest
minecraftServer:
  serverName: Wither Storm Bedrock Server
  levelName: WitherStorm
  serverPort: 19136
  eula: "TRUE"
  version: LATEST
  difficulty: normal
  maxPlayers: 10
  gameMode: survival
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  serviceType: LoadBalancer
  onlineMode: false
  texturepackRequired: true
persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft-witherstorm-ceph
