---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: ai-system
      version: 1.16.10
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
    - kind: Secret
      name: n8n-values-secret
