---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: n8n
spec:
  sourcePVC: n8n-main-persistence
  trigger:
    schedule: "2 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: ceph-block
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    parallelism: 2
    repository: n8n-volsync-secret
    retain:
      daily: 3
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
