sops:
  age:
    - recipient: age19gj66fq5v2veu940ftyj4pkw0w5tgxgddlyqnd00pnjzyndevurqx70g4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQnlxOWhMdjdtVUFtMndK
        blJVRE9oQjkxM1NKMnlGRjA1UTF3K2VyOEYwCmFYRnRkNUhhcXZTbDl5b3daT1Y4
        Q2VMUTFjRTVxV0V0azMwbFlmcVhZR3cKLS0tIE5DejlEalE2NkJwOTg2S013T1gw
        ZGMrZnlFRkc3OExtVG5LL0lNUE9KbDgKahujSEwyIqXtRnD/Yl2nVTC8lFW09Wec
        AmaF8fMO3qpQdBltgHpQ+1Q4C7WNzKrGQve33kt/dqyU0E7+H4hktA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-08T03:58:29Z"
  mac: ENC[AES256_GCM,data:ishxZe+Hny8+DYr1KiGwBL9iNmTvZxfxHwpElMk3rN8FlWgzIGXuHfIPGORW3lyySj6HOdzvTN32fz+S90vIHinIp+tjNCV3M0gZA5C30Ou9Y/g3tABaabsqEnMmpGAKYMr0NU14HSn+u9wfQ47t3ebmglJDVq23FcMBeblgXTE=,iv:lDZ5lWW2q5VBZtb6ivzfG2gJgdEDN6dMv1fb+72+Srg=,tag:Xx6CSl1Ktf6bRor8mGpGdw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
