---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geysermc-pixelmon-config
  namespace: game-servers
data:
  config.yml: |
    bedrock:
      address: 0.0.0.0
      port: 19132
    java:
      address: 127.0.0.1
      port: 25565
      auth-type: offline
      forward-hostname: false
    motd:
      primary-motd: "Pixelmon"
      secondary-motd: "Catch 'em all on Kubernetes!"
      passthrough-motd: true
      max-players: 100
      passthrough-player-counts: true
      ping-passthrough-interval: 3
    gameplay:
      server-name: "Pixelmon Server"
      cooldown-type: crosshair
      command-suggestions: true
      show-coordinates: true
      disable-bedrock-scaffolding: false
      enable-custom-content: true
      force-resource-packs: true
      enable-integrated-pack: true
      forward-player-ping: false
      xbox-achievements-enabled: false
      max-visible-custom-skulls: 128
      custom-skull-render-distance: 32
      unusable-space-block: minecraft:barrier
    default-locale: system
    log-player-ip-addresses: true
    saved-user-logins:
      - ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername
    pending-authentication-timeout: 120
    notify-on-new-bedrock-update: true
    advanced:
      cache-images: 0
      scoreboard-packet-threshold: 20
      bedrock:
        compression-level: 6
        validate-bedrock-login: false
        mtu: 1400
    enable-metrics: true
    debug-mode: false
    config-version: 7
