providers:
  openAI:
    apiKey: ENC[AES256_GCM,data:VZ92XprCxV8Kn/A=,iv:vR7u0erKG+j4uhnJiGCqKxf/cZGOzgNjXfwTILljS14=,tag:Unzrm+VuMTqW/QWWDR9vpw==,type:str]
sops:
  age:
    - recipient: age19gj66fq5v2veu940ftyj4pkw0w5tgxgddlyqnd00pnjzyndevurqx70g4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxejE4a2pqV1hyc2h1TG9v
        SHdzVW1EcjRPZ2hEd1RnamlpN0RvT1NaOFdFClpMRVh1Rk5SbVNmWE1YUUhIVnly
        akNoVUxoTmczdHVZWlJtQnBrTHhWS28KLS0tIFdkcDNHYnJWTHE1YjJSNFBHT0lw
        Qk9vbUtDN1hBK2JTU3grY0FPR2ZzWVkKLAQrMtDK9593m4Bu6M8l1Ic9POCb3n4X
        H6ucoChAAi/Y97hGGS6dcEd17JwUVIvojhVNDrV2lexD9tEo52SXGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-08T03:58:29Z"
  mac: ENC[AES256_GCM,data:N0SJYxSTOzMjtxFnf+lBNVwZ8Mo4cBxc9A/4SWNWeZ8zAKaWB85BM4sPXnV3MY6BcdAkDyiW5LpVtkCWbM/HvXul6b3xXdDKEm21Slfpukek1RD/aTPdIa/Auu2G5CVy/p6MRGTUH89PThiSHL+EYXuH9QK1z+IKazNFmYv2Ik4=,iv:1UR1owIXl8RiVtGemDM0btocUXneb9h2UOppWJNa+sQ=,tag:aL85a8meG16Ccu47BrvWVA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
