---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: ai-system
  labels:
    flux-defaults: "true"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kagent
  valuesFrom:
    - kind: ConfigMap
      name: kagent-values
    - kind: Secret
      name: kagent-values-secret
