---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmangos-ptr-mangosd-logs
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
