---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmangos-cores
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ceph-block
