---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: security-system
  labels:
    flux-defaults: "true"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: falco-exporter
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: false
      namespace: default
    prometheusRules:
      enabled: false
