#!/usr/bin/env bash

# TODO: Doesn't have multi-arch images
set -eou pipefail

# Ignore if namespace already exists
[[ ! $(kubectl get ns argocd) ]] && kubectl create ns argocd

# This will create a new namespace, argocd, where Argo CD services and application resources will live.
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# The initial password is autogenerated to be the pod name of the Argo CD API server. This can be retrieved with the command:
# Note: Must be done manually.
# kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2

argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default