---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: observability
spec:
  path: "./apps/base/observability/grafana/app"
  wait: true
  dependsOn:
    - name: cert-manager
      namespace: network-system
  targetNamespace: observability
  sourceRef:
    kind: ExternalArtifact
    name: grafana
    namespace: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: observability
spec:
  path: "./apps/base/observability/grafana/instance"
  wait: true
  dependsOn:
    - name: grafana
      namespace: observability
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  targetNamespace: observability
  sourceRef:
    kind: ExternalArtifact
    name: grafana-instance
    namespace: flux-system
