---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app democratic-csi
  namespace: democratic-csi
  labels:
    flux-defaults: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: *app
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      version: 0.15.1
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: democratic-csi-values
