apiVersion: v1
kind: Secret
metadata:
  name: minecraft-rcon
  namespace: game-servers
type: Opaque
stringData:
  rcon-password: ENC[AES256_GCM,data:gAYP5VK/26E=,iv:iWNuUfWkT4yKDXzaEanSQMKmr8vv3D2ubhuvfzCeM7k=,tag:ogs1Mzvgh15s3pIzF2RaDQ==,type:str]
sops:
  age:
    - recipient: age19gj66fq5v2veu940ftyj4pkw0w5tgxgddlyqnd00pnjzyndevurqx70g4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZVFOVUcrYkgyTU04QUpx
        ODVIa3RodFhLdHM2aVVHQWRLWVJjY1d4cjNRCnlLampjSVNiQm9hWXJoY2JVNHN6
        UlVEbVAraXN3Yi9ZZVlXWFR6dHVXbFEKLS0tIDlGdThUejVIeS9pZG84bDJUZnpi
        L21jSjZYQTNPcUxULzRhN0g2NXFWemcKcrv10p3PQrvN4tEH1/gz5M0myy0eDLSj
        2Ch+miySQRbW/IYe+bTQVybCsv0CdlCEtNzUc5VzVtcZnWn9tl9Mxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T21:37:14Z"
  mac: ENC[AES256_GCM,data:rsRoA82BiXT1kgxcFxh+pkklLGj60BdXY1ps3YViOZfsih5QCnQuJ2fsh+xDwtaJQs7x1jzUIXR/GW5TIjyyBI+wdd4eA2sp41nCTMyDd4D+PONvdM4GxVVFim09cDa+43QXwZYwH4h5RvPCipLSLPGY43cl1k187ugbN83dZNc=,iv:34f35VFTSHOucueZW0bZJFQ9ZhDh0rBMnPGTSy8c6Do=,tag:mDDH4GPCGcB1rllhZ3Tkug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
