---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpa
  namespace: observability
spec:
  path: "./apps/base/observability/vpa/app"
  wait: false
  targetNamespace: observability
  sourceRef:
    kind: ExternalArtifact
    name: vpa
    namespace: flux-system
