---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  path: "./apps/base/nginx-ingress/nginx-ingress/app"
  wait: true
  targetNamespace: nginx-ingress
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
