---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: security-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      version: 3.23.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper-charts
        namespace: flux-system
      interval: 10m
  values:
    psp:
      enabled: false
