minecraftServer:
  ops: ENC[AES256_GCM,data:fBrrkOMazPQPoTwPFjmW0vCaNmzf,iv:RXm8vAJcZMyvTOzh7DU7R/z/zwldKaTQNle1+dBIgEA=,tag:GmKuzVREMWggUz6uHJ/aOw==,type:str]
sops:
  age:
    - recipient: age19gj66fq5v2veu940ftyj4pkw0w5tgxgddlyqnd00pnjzyndevurqx70g4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoKzlXV0xtZ2NPVHg0Y2ht
        MitzTDVqczB3SS95c1dVRlNWVmlMZSsyU0RBCm5pYW92dlpPeEIvWVk3U01sTDZQ
        RCtNRlBGa3dSZ3ZQbHJQTVVPNERDK2cKLS0tIFN3allQdTczS2JiKzdHZjkwcWwz
        dW5uWFFmcGtsMHNrbURLdjlFLzdRL2cKLLXcqEsEqDxnR26OZgpVGTgOQm+bd96b
        kkW3R9rnafOYwYqTcQq+P57i7NkOobxkd9N0XMTM0VEdgvviCvQ2hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-08T03:58:29Z"
  mac: ENC[AES256_GCM,data:SdopWaqY5RnHxFUdREDsV7reKWKGpZnw1TyHtiaT15oR8jGA2zDfdhM7FIhozBgw9Snve0TJCItwOAceFZ90y1O+N8xYzqtakhUrma089kaREQy2ul5qHDzyMnd/x4mZ87O5sGVhWVTI9YrkMmWFSPRGXMMmYu1MwXM4f8gaTEs=,iv:bW34D+7jZQurqG5Dexkdn4H9HtFyb0cVKqIlZGTnNKU=,tag:EkANiYBdDIAwyYFvagXohg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
