---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  merge_group:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: false
        type: boolean
        required: true
      logLevel:
        description: Log Level
        default: info
        type: choice
        options:
          - debug
          - info
          - warn
          - error
          - fatal
        required: false
      version:
        description: Renovate Version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - .github/renovate.json5
      - .github/renovate/**.json5

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: "${{ steps.app-token.outputs.token }}"


      - name: Renovate
        uses: renovatebot/github-action@0b17c4eb901eca44d018fb25744a50a74b2042df # v46.1.4
        env:
          LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
          RENOVATE_DRY_RUN: "${{ inputs.dryRun }}"
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
        with:
          configurationFile: .github/renovate.json5
          token: "x-access-token:${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ inputs.version || 'latest' }}"
